# Simple Kubernetes Pod to deploy the app contained in pauljmartin16/getting-starged-k8s
# docker pull pauljmartin16/getting-starged-k8s:1.0
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: main-ctr
      image: nigelpoulton/nginxadapter:1.0
      ports:
      - containerPort: 80
    - name: helper-ctr
      image: nginx/nginx-prometheus-exporter
      args: ["-nginx.scrape-uri", "http://localhost/nginx_status"]
      ports:
      - containerPort: 9113
