# Simple Kubernetes Pod to deploy the app contained in pauljmartin16/getting-starged-k8s
# docker pull pauljmartin16/getting-starged-k8s:1.0
apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    name: web
spec:
  containers:
    - name: web-ctr
      image: pauljmartin16/getting-starged-k8s:1.0
      ports:
        - containerPort: 8080
